# Generated by Django 4.2 on YYYY-MM-DD HH:MM
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Route",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("origin", models.CharField(max_length=3)),
                ("destination", models.CharField(max_length=3)),
                ("airline", models.CharField(max_length=2)),
                ("baseline_price", models.FloatField()),
                ("threshold", models.FloatField(default=0.5)),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name="PriceHistory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("price", models.FloatField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("route", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="monitor.route")),
            ],
        ),
    ]
